# 제로베이스 데이터 사이언스 스쿨 3기 SQL 과제 2
- 유가 데이터 분석

### 8문제 총 100점

- 1번 5점
- 2번 5점
- 3번 10점
- 4번 30점
- 5번 10점
- 6번 10점
- 7번 15점
- 8번 15점

### 1 ~ 8번 모두 본 노트북 파일에 답안 작성해서 제출해주세요 :)

---

문제 1.

주유소 데이터를 저장할 테이블을 다음의 구조로 생성하세요. (PDF 파일 참고)

In [1]:
import mysql.connector

conn = mysql.connector.connect(
    host = "database-1.c93l4fp83jyc.us-east-2.rds.amazonaws.com",
    port = 3306,
    user = 'admin',
    password = 'zerobase',
    database = 'oneday'
)

cur = conn.cursor(buffered = True)

In [2]:
#주유소 브랜드 테이블 생성
cur.execute("""CREATE TABLE GAS_BRAND (
    id int NOT NULL auto_increment PRIMARY KEY,
    name varchar(16)
)""")

conn.commit()

In [3]:
#주유소 정보 테이블 생성
cur.execute("""CREATE TABLE GAS_STATION(
    id int NOT NULL auto_increment PRIMARY KEY,
    brand int,
    name varchar(64),
    city char(2),
    gu varchar(10),
    address varchar(128),
    gasoline int,
    diesel int,
    self boolean,
    car_wash boolean,
    charging_station boolean,
    car_maintenance boolean,
    convenience_store boolean,
    24_hours boolean,
    lat decimal(16,14),
    lng decimal(17,14),
    FOREIGN KEY (brand) REFERENCES GAS_BRAND(id)
);""")

conn.commit()

문제 2.

Python 코드로 GAS_BRAND 데이터를 다음과 같이 입력하고 확인하세요. (PDF 파일 참고)

In [4]:
sql = "INSERT INTO GAS_BRAND (Name) VALUES ('SK에너지'), ('현대오일뱅크'), ('GS칼텍스'), ('S-OIL'), ('알뜰주유소'), ('자가상표')"
cur.execute(sql)

conn.commit()

제출 1.
- Table 생성 결과 : Desc GAS_BRAND; Desc GAS_STATION;

In [5]:
cur.execute("desc GAS_BRAND")
result = cur.fetchall()

for row in result:
    print(row)

('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('name', 'varchar(16)', 'YES', '', None, '')

In [6]:
cur.execute("desc GAS_STATION")
result = cur.fetchall()

for row in result:
    print(row)

('id', 'int', 'NO', 'PRI', None, 'auto_increment')
('brand', 'int', 'YES', 'MUL', None, '')
('name', 'varchar(64)', 'YES', '', None, '')
('city', 'char(2)', 'YES', '', None, '')
('gu', 'varchar(10)', 'YES', '', None, '')
('address', 'varchar(128)', 'YES', '', None, '')
('gasoline', 'int', 'YES', '', None, '')
('diesel', 'int', 'YES', '', None, '')
('self', 'tinyint(1)', 'YES', '', None, '')
('car_wash', 'tinyint(1)', 'YES', '', None, '')
('charging_station', 'tinyint(1)', 'YES', '', None, '')
('car_maintenance', 'tinyint(1)', 'YES', '', None, '')
('convenience_store', 'tinyint(1)', 'YES', '', None, '')
('24_hours', 'tinyint(1)', 'YES', '', None, '')
('lat', 'decimal(16,14)', 'YES', '', None, '')
('lng', 'decimal(17,14)', 'YES', '', None, '')

제출 2.
- GAS_BRAND 조회 결과 : SELECT * FROM GAS_BRAND;

In [7]:
cur.execute("select * from GAS_BRAND")
result = cur.fetchall()

for row in result:
    print(row)

(1, 'SK에너지')
(2, '현대오일뱅크')
(3, 'GS칼텍스')
(4, 'S-OIL')
(5, '알뜰주유소')
(6, '자가상표')

문제 3.

다음의 함수와 그 함수를 테스트하는 코드를 작성하세요. (PDF 파일 참고)

- 화폐단위 문자형을 입력받아 숫자형으로 반환하는 함수 (테스트 입력 : ‘1,000’)
- 주유소 브랜드를 입력하면 GAS_BRAND 데이터를 참고하여 ID 를 반환하는 함수 (테스트 입력 : ‘SK에너지’) - 주소를 입력받아 구 이름을 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)
- 주소를 입력받아 위도, 경도를 반환하는 함수 (테스트 입력 : ‘서울시 강남구 헌릉로 730’)

제출 3.
- 각 함수 및 테스트 코드와 실행결과

In [8]:
#주유소 정보 셀레니움으로 추출
from selenium import webdriver
from selenium.webdriver.common.by import By
from bs4 import BeautifulSoup
import time
import pandas as pd
import numpy as np
from tqdm import tqdm_notebook

import googlemaps

gmaps_key = 'AIzaSyCiHXsM5pgR02fjYgLbDPhqE3Je4p1PBQg '
gmaps = googlemaps.Client(key=gmaps_key)

In [9]:
#화폐 단위 문자형을 입력받아 숫자형으로 반환 format 함수
#스크랩 중간에 디젤 값이 없는 주유소 발생,,
def thou_format(str):
    if s:
        return int(str.replace(",", "")) 
    else:
        return 0

def thou_format(s):
    if s:
        return int(s.replace(",", ""))
    else:
        return 0


#주유소 브랜드를 입력하면 gasbrand 데이터를 받아 id를 반환하는 함수
def station_id(brand):
    sql = "SELECT * FROM GAS_BRAND"
    cur.execute(sql)
    result = cur.fetchall()
    for i in result:
        if i[1] == brand:
            return i[0]
        elif brand == '알뜰(ex)':
            return 5
        elif brand == 'HD현대오일뱅크':
            return 2

#주소를 입력받아 구 이름을 반환하는 함수 split
def extrace_gu(address):
    return address.split(" ")[1]

#주소를 입력 받아 위도, 경도를 반환하는 함수 gmap
def get_latlng(address):
    tmp = gmaps.geocode(address, language = 'ko')
    lat = tmp[0].get('geometry')['location']['lat']
    lng = tmp[0].get('geometry')['location']['lng']
    
    return lat, lng

문제 4.

Python 코드에서 주유소 페이지에서 데이터를 가져올때, GAS_STATION 테이블에 바로 입력하도록 수정하세요. (앞서 생 성한 함수활용)
- 주의. city 는 ‘서울’ 로 고정, 부가정보 데이터 타입
- 입력된 데이터의 총 갯수를 쿼리하여 결과를 확인합니다. - 입력된 데이터 상위 10개를 쿼리하여 결과를 확인합니다.


제출 4.
- 주유소 데이터 관련 코드 (ipynb)

In [10]:
#페이지 접근
driver = webdriver.Chrome()
driver.maximize_window()
url = "https://www.opinet.co.kr/searRgSelect.do"
driver.get(url)

time.sleep(0.5)

#서울 고정
seoul = driver.find_element(By.CSS_SELECTOR, '#SIDO_NM0')
sido_list = seoul.find_elements(By.CSS_SELECTOR, 'option')
sido_names = [option.get_attribute('value') for option in sido_list]
sido_names = sido_names[1:]
seoul.send_keys(sido_names[0]) #서울특별시 클릭

time.sleep(0.5)

#3. 구별 선택
gu_list_raw = driver.find_element(By.CSS_SELECTOR, '#SIGUNGU_NM0') #부모태그
gu_list = gu_list_raw.find_elements(By.CSS_SELECTOR, 'option')
gu_names = [option.get_attribute('value') for option in gu_list if option.get_attribute('value')] #공백 제거 맨 앞이 value값이 없음

for i in tqdm_notebook(range(len(gu_names))):
    gu_selector = f'#SIGUNGU_NM0 > option:nth-child({i+2})'
    driver.find_element(By.CSS_SELECTOR, gu_selector).click()
    station_items = driver.find_elements(By.CSS_SELECTOR, '#body1 > tr') #주유소 목록
    
    time.sleep(0.2)
    
    for idx in range(len(station_items)):
        detail_selector = f'#body1 > tr:nth-child({idx+1}) > td.rlist > a'
        driver.find_element(By.CSS_SELECTOR, detail_selector).click()
        
        name = driver.find_element(By.CSS_SELECTOR, '.header #os_nm').get_attribute('innerText')
        address = driver.find_element(By.CSS_SELECTOR, '#rd_addr').get_attribute('innerText') 
        gu = extrace_gu(address)
        gasoline_raw = driver.find_element(By.CSS_SELECTOR, '#b027_p').get_attribute('innerText')
        gasoline = thou_format(gasoline_raw)
        
        diesel_raw = driver.find_element(By.CSS_SELECTOR, '#d047_p').get_attribute('innerText')
        diesel = thou_format(diesel_raw)
        brand_raw = driver.find_element(By.CSS_SELECTOR, '#poll_div_nm').get_attribute('innerText')
        brand = station_id(brand_raw)
        
        try:
            driver.find_element(By.CSS_SELECTOR, '#self_icon').get_attribute('alt')
            is_self = 1 #true로 넣어야 할까 1로 넣어야 할까? boolean data type
        except:
            is_self = 0
        
        cwsh_yn = 0 if 'off' in driver.find_element(By.CSS_SELECTOR, '.service #cwsh_yn').get_attribute('src').split('/')[-1] else 1
        lpg_yn = 0 if 'off' in driver.find_element(By.CSS_SELECTOR, '.service #lpg_yn').get_attribute('src').split('/')[-1] else 1
        main_yn = 0 if 'off' in driver.find_element(By.CSS_SELECTOR, '.service #maint_yn').get_attribute('src').split('/')[-1] else 1
        cvs_yn = 0 if 'off' in driver.find_element(By.CSS_SELECTOR, '.service #cvs_yn').get_attribute('src').split('/')[-1] else 1
        sel24_yn = 0 if 'off' in driver.find_element(By.CSS_SELECTOR, '.service #sel24_yn').get_attribute('src').split('/')[-1] else 1

        lat, lng = get_latlng(address)
        
        
        sql = "INSERT INTO GAS_STATION (brand, name, city, gu, address, gasoline, diesel, self, car_wash, charging_station, car_maintenance, convenience_store, 24_hours, lat, lng) \
                VALUES (%s, %s, '서울', %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);"

        # 변수 값을 대체하여 SQL 쿼리 실행
        cur.execute(sql, (brand, name, gu, address, gasoline, diesel, is_self, cwsh_yn, lpg_yn, main_yn, cvs_yn, sel24_yn, lat, lng))
        conn.commit()
        
driver.quit()

C:\Users\sori4\AppData\Local\Temp/ipykernel_25888/3267827429.py:23: TqdmDeprecationWarning: This function will be removed in tqdm==5.0.0
Please use `tqdm.notebook.tqdm` instead of `tqdm.tqdm_notebook`
  for i in tqdm_notebook(range(len(gu_names))):

  0%|          | 0/25 [00:00<?, ?it/s]

In [11]:
#총 개수 확인
cur.execute("SELECT COUNT(*) FROM GAS_STATION")
result = cur.fetchall()

for row in result:
    print(row[0])

433

In [12]:
#데이터 상위 10개  확인
cur.execute("SELECT * FROM GAS_STATION LIMIT 5")
result = cur.fetchall()

for row in result:
    print(row)

(1, 2, '삼성동주유소', '서울', '강남구', '서울 강남구 테헤란로 619 (삼성동)', 1719, 1705, 1, 1, 0, 0, 0, 0, Decimal('37.50985760000000'), Decimal('127.06511010000000'))
(2, 1, '(주)보성 세곡주유소', '서울', '강남구', '서울 강남구 헌릉로 731 (세곡동)', 1723, 1663, 1, 1, 0, 0, 0, 0, Decimal('37.46715650000000'), Decimal('127.11870810000000'))
(3, 2, 'HD현대오일뱅크㈜직영 산성셀프주유소', '서울', '강남구', '서울 강남구 헌릉로 730', 1748, 1678, 1, 1, 0, 0, 0, 0, Decimal('37.46656750000000'), Decimal('127.11908030000000'))
(4, 2, 'HD현대오일뱅크㈜직영 도곡셀프주유소', '서울', '강남구', '서울 강남구 남부순환로 2718 (도곡2동)', 1754, 1699, 1, 1, 0, 1, 0, 0, Decimal('37.48546230000000'), Decimal('127.04321810000000'))
(5, 3, '방죽주유소', '서울', '강남구', '서울 강남구 밤고개로 215 (율현동)', 1757, 1689, 1, 1, 0, 0, 0, 0, Decimal('37.47499260000000'), Decimal('127.10688660000000'))

문제 5.

시각화 프로젝트를 위하여 다음의 규칙으로 쿼리하여 CSV 파일로 저장합니다. (Python 코드로 작성)
- 전체 데이터를 가져오는데, 주유소 브랜드 아이디 대신 브랜드명이 표시되어야 합니다. (정렬 : 주유소 매장 아이디 순)
- 다음의 형식으로 저장되어야 함 (브랜드 이름, 칼럼 명 주의, id : GAS_STORE.id)

제출 5.
- 시각화 프로젝트 관련 코드 (ipynb), 결과 파일 (csv)

In [13]:
#데이터를 가져올 때 브랜드 아이디 대신 브랜드명이 표시
sql = "SELECT s.id, b.name 'brand', s.name, s.city, s.gu, s.address, s.gasoline, s.diesel, s.self, s.car_wash, s.charging_station, s.car_maintenance, \
s.convenience_store, s.24_hours, s.lat, s.lng \
FROM GAS_STATION s, GAS_BRAND b \
WHERE b.id = s.brand ORDER BY s.id"

cur.execute(sql)
result = cur.fetchall()

for row in result:
    print(row)

(1, '현대오일뱅크', '삼성동주유소', '서울', '강남구', '서울 강남구 테헤란로 619 (삼성동)', 1719, 1705, 1, 1, 0, 0, 0, 0, Decimal('37.50985760000000'), Decimal('127.06511010000000'))
(2, 'SK에너지', '(주)보성 세곡주유소', '서울', '강남구', '서울 강남구 헌릉로 731 (세곡동)', 1723, 1663, 1, 1, 0, 0, 0, 0, Decimal('37.46715650000000'), Decimal('127.11870810000000'))
(3, '현대오일뱅크', 'HD현대오일뱅크㈜직영 산성셀프주유소', '서울', '강남구', '서울 강남구 헌릉로 730', 1748, 1678, 1, 1, 0, 0, 0, 0, Decimal('37.46656750000000'), Decimal('127.11908030000000'))
(4, '현대오일뱅크', 'HD현대오일뱅크㈜직영 도곡셀프주유소', '서울', '강남구', '서울 강남구 남부순환로 2718 (도곡2동)', 1754, 1699, 1, 1, 0, 1, 0, 0, Decimal('37.48546230000000'), Decimal('127.04321810000000'))
(5, 'GS칼텍스', '방죽주유소', '서울', '강남구', '서울 강남구 밤고개로 215 (율현동)', 1757, 1689, 1, 1, 0, 0, 0, 0, Decimal('37.47499260000000'), Decimal('127.10688660000000'))
(6, 'SK에너지', '자곡셀프주유소', '서울', '강남구', '서울 강남구 밤고개로 120 (자곡동)', 1757, 1679, 1, 1, 0, 0, 0, 0, Decimal('37.48340020000000'), Decimal('127.10404580000000'))
(7, 'SK에너지', '오일프러스 셀프', '서울', '강남구', '서울 강남구 남부순환로 2651 (도곡동)', 1764, 1704, 1, 1, 0, 1, 0, 1, Decimal('37.48583900000000'), Decimal('127.03967210000000'))
(8, 'S-OIL', '극동유화㈜ 개나리주유소', '서울', '강남구', '서울 강남구 언주로 423 (역삼동)', 1765, 1705, 1, 1, 0, 1, 0, 1, Decimal('37.50007760000000'), Decimal('127.03854190000000'))
(9, 'SK에너지', '(주)중앙에너비스 수서지점', '서울', '강남구', '서울 강남구 광평로 202 (수서동)', 1767, 1667, 1, 1, 0, 0, 0, 0, Decimal('37.48410530000000'), Decimal('127.09504010000000'))
(10, 'S-OIL', '일원주유소', '서울', '강남구', '서울 강남구 양재대로55길 3 (일원동)', 1767, 1699, 1, 0, 0, 0, 0, 0, Decimal('37.49425010000000'), Decimal('127.09419970000000'))
(11, '현대오일뱅크', 'HD현대오일뱅크㈜직영 유진주유소', '서울', '강남구', '서울 강남구 논현로 152 (도곡동)', 1769, 1714, 0, 1, 0, 1, 0, 0, Decimal('37.48743160000000'), Decimal('127.03999760000000'))
(12, 'GS칼텍스', '지에스칼텍스㈜에너지플러스허브GS타워', '서울', '강남구', '서울 강남구 논현로 516 (역삼동)', 1804, 1799, 1, 0, 0, 1, 0, 1, Decimal('37.50270829999999'), Decimal('127.03639560000000'))
(13, 'S-OIL', '(주)선진도곡주유소', '서울', '강남구', '서울 강남구 도곡로 162 (도곡동)', 1825, 1765, 0, 1, 0, 1, 0, 0, Decimal('37.48782540000000'), Decimal('127.04668760000000'))
(14, 'SK에너지', 'SK에너지㈜ 진달래주유소', '서울', '강남구', '서울 강남구 도곡로 208', 1825, 1739, 0, 1, 0, 0, 0, 0, Decimal('37.49229500000000'), Decimal('127.04185980000000'))
(15, 'SK에너지', 'SK서광주유소', '서울', '강남구', '서울 강남구 역삼로 142', 1835, 1715, 1, 1, 0, 1, 0, 1, Decimal('37.49434240000000'), Decimal('127.03509150000000'))
(16, 'SK에너지', '(유)동하석유 힐탑셀프주유소', '서울', '강남구', '서울 강남구 논현로 640', 1837, 1797, 1, 1, 0, 0, 0, 1, Decimal('37.51068870000000'), Decimal('127.03256890000000'))
(17, 'SK에너지', '대동석유 압구정주유소', '서울', '강남구', '서울 강남구 언주로 842 (신사동)', 1857, 1797, 1, 1, 0, 0, 0, 1, Decimal('37.52534310000000'), Decimal('127.03382420000000'))
(18, 'GS칼텍스', '대양산업(주) 개포주유소', '서울', '강남구', '서울 강남구 양재대로 339', 1858, 1848, 1, 1, 0, 0, 0, 0, Decimal('37.47224090000000'), Decimal('127.05151340000000'))
(19, 'SK에너지', '대교셀프주유소', '서울', '강남구', '서울 강남구 강남대로 640 (신사동)', 1890, 1840, 1, 0, 0, 0, 0, 1, Decimal('37.52812920000000'), Decimal('127.03555370000000'))
(20, 'GS칼텍스', '지에스칼텍스㈜ 삼성로주유소', '서울', '강남구', '서울 강남구 삼성로 563 (삼성동)', 1959, 1954, 1, 1, 0, 0, 0, 1, Decimal('37.51397499999999'), Decimal('127.05612740000000'))
(21, 'GS칼텍스', '지에스칼텍스㈜ 은마주유소', '서울', '강남구', '서울 강남구 영동대로 235', 1979, 1964, 0, 1, 0, 1, 0, 1, Decimal('37.50007210000000'), Decimal('127.06728480000000'))
(22, '현대오일뱅크', 'HD현대오일뱅크㈜직영 신사현대주유소', '서울', '강남구', '서울 강남구 도산대로 163 (신사동)', 1998, 1934, 0, 1, 0, 0, 0, 0, Decimal('37.51952050000000'), Decimal('127.02631710000000'))
(23, 'GS칼텍스', '대성석유(주)동호주유소', '서울', '강남구', '서울 강남구 봉은사로113길 51', 2099, 1999, 0, 1, 0, 0, 0, 0, Decimal('37.51848600000000'), Decimal('127.06466550000000'))
(24, 'GS칼텍스', '지에스칼텍스(주)학여울주유소', '서울', '강남구', '서울 강남구 남부순환로 3170 (일원2동)', 2138, 2079, 0, 1, 0, 0, 0, 0, Decimal('37.49467620000000'), Decimal('127.07783050000000'))
(25, '현대오일뱅크', 'HD현대오일뱅크㈜직영 한양주유소', '서울', '강남구', '서울 강남구 압구정로 302 (신사동)', 2153, 2096, 0, 1, 0, 0, 0, 0, Decimal('37.52886810000000'), Decimal('127.03410460000000'))
(26, 'S-OIL', '명품주유소', '서울', '강남구', '서울 강남구 도곡로 249 (역삼동)', 2228, 2087, 1, 1, 0, 0, 0, 1, Decimal('37.49427040000000'), Decimal('127.04550930000000'))
(27, 'GS칼텍스', '(주)소모 쎈트럴주유소', '서울', '강남구', '서울 강남구 삼성로 335', 2237, 2182, 0, 1, 0, 0, 0, 0, Decimal('37.50142090000000'), Decimal('127.05914080000000'))
(28, 'SK에너지', '대청주유소', '서울', '강남구', '서울 강남구 개포로 654 (일원동)', 2326, 2196, 0, 1, 0, 0, 0, 0, Decimal('37.49247370000001'), Decimal('127.08567900000000'))
(29, '현대오일뱅크', '㈜새서울석유 새서울주유소', '서울', '강남구', '서울 강남구 압구정로 154', 2348, 2198, 0, 1, 0, 0, 0, 1, Decimal('37.52583500000000'), Decimal('127.02654220000000'))
(30, 'SK에너지', 'SK논현주유소', '서울', '강남구', '서울 강남구 논현로 747 (논현동)', 2440, 2355, 0, 1, 0, 1, 0, 1, Decimal('37.51863680000000'), Decimal('127.02823800000000'))
(31, '현대오일뱅크', '(주)제이제이네트웍스 제이제이주유소', '서울', '강남구', '서울 강남구 언주로 716', 2560, 2450, 0, 1, 0, 0, 0, 1, Decimal('37.51764720000000'), Decimal('127.03573490000000'))
(32, 'GS칼텍스', '(주)만정에너지 삼보주유소', '서울', '강남구', '서울 강남구 봉은사로 433 (삼성동)', 2598, 2560, 0, 1, 0, 0, 0, 0, Decimal('37.51152070000000'), Decimal('127.04717160000000'))
(33, '현대오일뱅크', '재건에너지 재정제2주유소 고속셀프지점', '서울', '강동구', '서울특별시 강동구 천호대로 1246 (둔촌제2동)', 1729, 1659, 1, 1, 0, 0, 0, 0, Decimal('37.53651330000000'), Decimal('127.14935880000000'))
(34, '현대오일뱅크', '구천면주유소', '서울', '강동구', '서울 강동구 구천면로 357 (암사동)', 1744, 1655, 0, 0, 0, 0, 0, 0, Decimal('37.55045980000000'), Decimal('127.13823160000000'))
(35, 'SK에너지', '방아다리주유소', '서울', '강동구', '서울 강동구 동남로 811 (명일동)', 1765, 1695, 1, 1, 0, 0, 0, 0, Decimal('37.54904450000000'), Decimal('127.15082290000000'))
(36, 'GS칼텍스', '(주)소모 신월주유소', '서울', '강동구', '서울 강동구 양재대로 1323 (성내동)', 1776, 1678, 1, 1, 0, 0, 0, 0, Decimal('37.53049330000000'), Decimal('127.12899200000000'))
(37, 'GS칼텍스', '대성석유(주)길동주유소', '서울', '강동구', '서울 강동구 천호대로 1168', 1776, 1678, 0, 1, 0, 0, 0, 0, Decimal('37.53342290000000'), Decimal('127.14117250000000'))
(38, 'GS칼텍스', '(주)삼표에너지 고덕주유소', '서울', '강동구', '서울 강동구 고덕로 39 (암사동)', 1799, 1719, 1, 1, 0, 0, 1, 0, Decimal('37.55504900000000'), Decimal('127.12979290000000'))
(39, 'SK에너지', 'sk해뜨는주유소', '서울', '강동구', '서울 강동구 상일로 132 (강일동)', 1819, 1729, 1, 1, 0, 1, 0, 0, Decimal('37.55450850000000'), Decimal('127.17241540000000'))
(40, 'GS칼텍스', '지에스칼텍스㈜ 동서울주유소', '서울', '강동구', '서울 강동구 천호대로 1456 (상일동)', 1821, 1764, 1, 1, 0, 0, 0, 0, Decimal('37.55110280000000'), Decimal('127.16964010000000'))
(41, 'GS칼텍스', '(주)소모 성내주유소', '서울', '강동구', '서울 강동구 올림픽로 578 (성내동)', 1848, 1748, 1, 1, 0, 1, 0, 0, Decimal('37.53137820000000'), Decimal('127.12732860000000'))
(42, 'S-OIL', '(주)퍼스트오일 코알라주유소', '서울', '강동구', '서울특별시 강동구 올림픽로 556 (성내동)', 1850, 1750, 1, 1, 0, 0, 0, 0, Decimal('37.52938080000000'), Decimal('127.12244080000000'))
(43, 'SK에너지', '주)지유에너지직영 오렌지주유소', '서울', '강동구', '서울 강동구 성안로 102 (성내동)', 1865, 1765, 0, 1, 0, 1, 0, 0, Decimal('37.53231400000000'), Decimal('127.13317810000000'))
(44, '현대오일뱅크', '천호현대주유소', '서울', '강동구', '서울 강동구 천중로 67 (천호동)', 1985, 1895, 0, 1, 0, 1, 0, 0, Decimal('37.54513310000000'), Decimal('127.12947300000000'))
(45, 'S-OIL', '광성주유소', '서울', '강동구', '서울 강동구 올림픽로 673 (천호동)', 2068, 2018, 0, 1, 0, 1, 0, 1, Decimal('37.54161170000000'), Decimal('127.12417310000000'))
(46, 'SK에너지', '북서울고속주유소', '서울', '강북구', '서울 강북구 삼양로 410 (수유동)', 1643, 1574, 1, 0, 0, 0, 0, 1, Decimal('37.64014480000000'), Decimal('127.01720500000000'))
(47, '현대오일뱅크', '(주)서울에너지 시민주유소', '서울', '강북구', '서울 강북구 인수봉로 185 (수유동)', 1643, 1574, 1, 0, 0, 0, 0, 0, Decimal('37.63620220000000'), Decimal('127.01282200000000'))
(48, 'GS칼텍스', '수유동주유소', '서울', '강북구', '서울 강북구 도봉로 395 (수유동)', 1643, 1573, 1, 1, 0, 0, 0, 1, Decimal('37.64215560000000'), Decimal('127.02958620000000'))
(49, '현대오일뱅크', '(주)석산에너지', '서울', '강북구', '서울 강북구 삼양로 316 (수유동)', 1643, 1574, 1, 0, 0, 0, 0, 0, Decimal('37.63163350000000'), Decimal('127.01793940000000'))
(50, 'S-OIL', '덕릉로주유소', '서울', '강북구', '서울 강북구 덕릉로 158 (번동)', 1663, 1584, 1, 1, 0, 0, 0, 0, Decimal('37.63497560000000'), Decimal('127.03131820000000'))
(51, 'GS칼텍스', '㈜지에스이앤알 미아주유소', '서울', '강북구', '서울 강북구 도봉로 122 (미아동)', 1665, 1645, 1, 1, 0, 0, 0, 0, Decimal('37.61999640000000'), Decimal('127.02903040000000'))
(52, 'S-OIL', '씨앤에스유통㈜ 미아셀프주유소', '서울', '강북구', '서울 강북구 도봉로 200 (미아동)', 1665, 1595, 1, 1, 0, 0, 0, 0, Decimal('37.62652920000000'), Decimal('127.02650020000000'))
(53, '현대오일뱅크', 'HD현대오일뱅크㈜직영 번동셀프주유소', '서울', '강북구', '서울 강북구 한천로 963 (번동)', 1667, 1597, 1, 1, 0, 1, 0, 1, Decimal('37.63558720000000'), Decimal('127.03304930000000'))
(54, 'SK에너지', 'SK에너지(주) 매일주유소', '서울', '강북구', '서울 강북구 삼양로 217 (미아동)', 1668, 1599, 1, 1, 0, 0, 1, 0, Decimal('37.62279770000000'), Decimal('127.01913560000000'))
(55, 'SK에너지', '세원주유소', '서울', '강북구', '서울 강북구 한천로 918 (번동)', 1698, 1648, 1, 1, 0, 0, 0, 0, Decimal('37.63425960000000'), Decimal('127.03773200000000'))
(56, 'SK에너지', '에덴주유소', '서울', '강북구', '서울 강북구 월계로 195 (번동)', 1699, 1629, 1, 1, 0, 1, 0, 0, Decimal('37.62169580000000'), Decimal('127.04553440000000'))
(57, 'GS칼텍스', '대성석유(주)신광주유소', '서울', '강북구', '서울 강북구 삼양로 484', 1699, 1599, 0, 1, 0, 1, 0, 0, Decimal('37.64640880000000'), Decimal('127.01532850000000'))
(58, 'SK에너지', '강서오곡셀프주유소', '서울', '강서구', '서울 강서구 벌말로 254 (오곡동)', 1627, 1587, 1, 1, 0, 0, 0, 1, Decimal('37.55396220000000'), Decimal('126.76842750000000'))
(59, '알뜰주유소', '목화주유소', '서울', '강서구', '서울 강서구 국회대로 251 (화곡동)', 1632, 1614, 1, 1, 0, 0, 0, 0, Decimal('37.53004030000000'), Decimal('126.86298250000000'))
(60, '알뜰주유소', '화곡역주유소', '서울', '강서구', '서울 강서구 강서로 154 (화곡동)', 1632, 1585, 1, 0, 0, 0, 0, 1, Decimal('37.54071860000000'), Decimal('126.84153030000000'))
(61, 'SK에너지', '(주)타이거오일 방화주유소', '서울', '강서구', '서울 강서구 방화동로 58-2 (방화동)', 1633, 1593, 1, 0, 0, 0, 0, 0, Decimal('37.56562740000000'), Decimal('126.81240820000000'))
(62, '알뜰주유소', '유턴주유소', '서울', '강서구', '서울 강서구 남부순환로 57', 1637, 1587, 1, 0, 0, 0, 0, 0, Decimal('37.55049010000000'), Decimal('126.81645040000000'))
(63, 'S-OIL', '스카이주유소', '서울', '강서구', '서울 강서구 개화동로 457 (방화동)', 1637, 1599, 1, 1, 0, 0, 1, 1, Decimal('37.57148580000000'), Decimal('126.80438060000000'))
(64, '알뜰주유소', '(주)뉴신정주유소', '서울', '강서구', '서울 강서구 곰달래로 207 (화곡동)', 1637, 1587, 0, 0, 0, 0, 0, 0, Decimal('37.53157960000000'), Decimal('126.85605240000000'))
(65, '현대오일뱅크', '행촌에너지 공항주유소', '서울', '강서구', '서울 강서구 개화동로 420 (개화동)', 1637, 1599, 1, 1, 0, 1, 1, 1, Decimal('37.57461100000000'), Decimal('126.80230290000000'))
(66, 'SK에너지', 'KH에너지(주)직영 KH외발산주유소', '서울', '강서구', '서울 강서구 방화대로 30', 1649, 1599, 1, 1, 1, 1, 1, 0, Decimal('37.54342080000000'), Decimal('126.81686300000000'))
(67, 'GS칼텍스', '지에스칼텍스㈜ 경인고속주유소', '서울', '강서구', '서울 강서구 국회대로 225 (화곡동)', 1659, 1624, 1, 1, 1, 1, 0, 1, Decimal('37.52962090000000'), Decimal('126.85979700000000'))
(68, 'SK에너지', '개화주유소', '서울', '강서구', '서울 강서구 양천로 57', 1677, 1637, 1, 1, 0, 0, 0, 0, Decimal('37.57350140000000'), Decimal('126.81009430000000'))
(69, 'S-OIL', '신화곡주유소', '서울', '강서구', '서울 강서구 국회대로 71', 1695, 1685, 1, 1, 0, 0, 0, 0, Decimal('37.52725790000000'), Decimal('126.84288960000000'))
(70, '현대오일뱅크', '현대오일뱅크 등촌주유소', '서울', '강서구', '서울 강서구 등촌로 189 (등촌동)', 1696, 1636, 0, 1, 0, 0, 0, 0, Decimal('37.54680800000000'), Decimal('126.86255450000000'))
(71, 'S-OIL', '하이웨이주유소', '서울', '강서구', '서울특별시 강서구 공항대로 432(화곡동)', 1698, 1678, 1, 1, 0, 0, 1, 1, Decimal('37.55466770000000'), Decimal('126.85480530000000'))
(72, '현대오일뱅크', 'HD현대오일뱅크㈜직영 양화교셀프주유소', '서울', '강서구', '서울 강서구 공항대로 653', 1699, 1665, 1, 1, 0, 0, 0, 0, Decimal('37.54733680000000'), Decimal('126.87747640000000'))
(73, 'SK에너지', '화곡현대주유소', '서울', '강서구', '서울 강서구 강서로 151 (화곡동)', 1714, 1676, 1, 1, 0, 0, 0, 1, Decimal('37.54026140000000'), Decimal('126.84119830000000'))
(74, 'SK에너지', '우장산주유소', '서울', '강서구', '서울 강서구 강서로 292 (내발산동)', 1725, 1678, 1, 0, 0, 0, 0, 0, Decimal('37.55249440000000'), Decimal('126.83330610000000'))
(75, 'GS칼텍스', '강서열린주유소', '서울', '강서구', '서울 강서구 등촌로 213 (등촌동)', 1728, 1678, 0, 1, 0, 0, 0, 0, Decimal('37.54871199999999'), Decimal('126.86306280000000'))
(76, 'SK에너지', '오션네트웍스(주) 서울식물원지점', '서울', '강서구', '서울 강서구 양천로 300', 1736, 1658, 1, 0, 0, 0, 0, 0, Decimal('37.57038720000000'), Decimal('126.83693060000000'))
(77, 'S-OIL', '(주)한진 김포공항주유소', '서울', '강서구', '서울 강서구 하늘길 259', 1740, 1640, 1, 1, 0, 0, 0, 0, Decimal('37.55077630000000'), Decimal('126.81555490000000'))
(78, '현대오일뱅크', 'HD현대오일뱅크㈜직영 가양주유소', '서울', '강서구', '서울 강서구 양천로 391 (가양동)', 1743, 1679, 0, 1, 0, 0, 0, 0, Decimal('37.56788020000000'), Decimal('126.85107870000000'))
(79, 'SK에너지', '세원제1주유소', '서울', '강서구', '서울 강서구 양천로 311 (가양동)', 1755, 1675, 1, 1, 0, 1, 0, 0, Decimal('37.56788020000000'), Decimal('126.85107870000000'))
(80, 'GS칼텍스', '대성석유(주) 마곡대성주유소', '서울', '강서구', '서울 강서구 강서로 457', 1756, 1688, 1, 0, 0, 0, 0, 0, Decimal('37.56634850000000'), Decimal('126.84044660000000'))
(81, 'SK에너지', 'SK KH에너지 가양주유소', '서울', '강서구', '서울 강서구 강서로 498 (가양동)', 1758, 1678, 0, 1, 0, 1, 1, 1, Decimal('37.56978230000000'), Decimal('126.84190220000000'))
(82, 'GS칼텍스', '대성석유(주) 관문주유소', '서울', '강서구', '서울 강서구 공항대로 314', 1766, 1698, 0, 1, 0, 1, 0, 0, Decimal('37.55772320000000'), Decimal('126.84252430000000'))
(83, 'GS칼텍스', '대성석유(주)방화대성주유소', '서울', '강서구', '서울 강서구 양천로 176', 1766, 1678, 1, 1, 0, 0, 1, 0, Decimal('37.57288150000000'), Decimal('126.82348210000000'))
(84, 'S-OIL', '(주)한진 김포공항제2주유소', '서울', '강서구', '서울 강서구 하늘길 112', 1774, 1714, 1, 0, 0, 0, 0, 0, Decimal('37.55675570000000'), Decimal('126.80847340000000'))
(85, 'GS칼텍스', '대성주유소', '서울', '강서구', '서울 강서구 강서로 472', 1778, 1698, 0, 1, 0, 1, 0, 0, Decimal('37.56750280000000'), Decimal('126.84141860000000'))
(86, 'SK에너지', '코리나(주)청룡주유소', '서울', '강서구', '서울 강서구 양천로 576', 1798, 1738, 0, 1, 0, 0, 0, 0, Decimal('37.55673250000000'), Decimal('126.86276500000000'))
(87, 'GS칼텍스', '박물관주유소', '서울', '강서구', '서울 강서구 양천로53길 97 (가양동)', 1798, 1728, 0, 1, 0, 1, 1, 0, Decimal('37.56578490000000'), Decimal('126.84512160000000'))
(88, 'S-OIL', '참솔에너지', '서울', '강서구', '서울 강서구 벌말로 281 (오곡동)', 1965, 1865, 1, 1, 0, 0, 0, 0, Decimal('37.55625190000000'), Decimal('126.76844910000000'))
(89, 'SK에너지', '염창동주유소', '서울', '강서구', '서울 강서구 양천로 720 (염창동)', 2083, 1984, 0, 1, 0, 0, 0, 0, Decimal('37.54911130000000'), Decimal('126.87579060000000'))
(90, '현대오일뱅크', '(주)엠오티이엔지 직영 삼화주유소', '서울', '관악구', '서울 관악구 보라매로 41', 1698, 1638, 0, 0, 0, 0, 0, 0, Decimal('37.49320180000000'), Decimal('126.92673660000000'))
(91, '알뜰주유소', '(주)연우에너지 신관주유소', '서울', '관악구', '서울 관악구 신림로 290 (신림동)', 1698, 1638, 1, 1, 0, 0, 0, 0, Decimal('37.48041300000000'), Decimal('126.93066650000000'))
(92, '현대오일뱅크', 'HD현대오일뱅크㈜직영 문성골주유소', '서울', '관악구', '서울 관악구 문성로 97 (신림동)', 1704, 1654, 0, 1, 0, 0, 0, 0, Decimal('37.47779410000000'), Decimal('126.91430220000000'))
(93, 'SK에너지', '대양석유(주)직영 보라매주유소', '서울', '관악구', '서울 관악구 보라매로 26 (봉천동)', 1709, 1654, 1, 1, 0, 0, 0, 0, Decimal('37.49168740000000'), Decimal('126.92716030000000'))
(94, 'SK에너지', '(주)한유에너지행운셀프주유소', '서울', '관악구', '서울 관악구 남부순환로 1883 (봉천동)', 1715, 1655, 1, 1, 0, 0, 0, 0, Decimal('37.47910830000000'), Decimal('126.95916970000000'))
(95, '현대오일뱅크', 'HD현대오일뱅크㈜직영 관악셀프주유소', '서울', '관악구', '서울 관악구 남부순환로 1520 (신림동)', 1719, 1664, 1, 0, 0, 0, 0, 0, Decimal('37.48246190000000'), Decimal('126.91946710000000'))
(96, 'SK에너지', 'SK에너지(주) 신봉천', '서울', '관악구', '서울 관악구 남부순환로 1880 (봉천동)', 1725, 1665, 0, 1, 0, 0, 1, 0, Decimal('37.47875720000000'), Decimal('126.95834320000000'))
(97, 'GS칼텍스', '서일석유(주)락성주유소', '서울', '관악구', '서울 관악구 남부순환로 1920 (봉천동)', 1725, 1665, 1, 1, 0, 1, 0, 1, Decimal('37.47717919999999'), Decimal('126.96238830000000'))
(98, 'SK에너지', 'SK에너지(주)직영 대공원주유소', '서울', '관악구', '서울 관악구 과천대로 921 (남현동)', 1725, 1665, 0, 1, 0, 1, 1, 0, Decimal('37.47285560000000'), Decimal('126.98215150000000'))
(99, 'S-OIL', '유림주유소', '서울', '관악구', '서울 관악구 신림로 176 (신림동)', 1748, 1698, 0, 1, 0, 1, 0, 1, Decimal('37.47372470000000'), Decimal('126.93488000000000'))
(100, '현대오일뱅크', '현대주유소', '서울', '관악구', '서울 관악구 난곡로 108 (신림동)', 1769, 1709, 0, 0, 0, 0, 0, 0, Decimal('37.46498240000000'), Decimal('126.91967450000000'))
(101, 'S-OIL', '관악시몬주유소', '서울', '관악구', '서울특별시 관악구 남부순환로 1753 (봉천동)', 1846, 1746, 0, 1, 0, 0, 0, 0, Decimal('37.48235850000000'), Decimal('126.94510100000000'))
(102, 'GS칼텍스', 'CJ대한통운㈜ 신림주유소', '서울', '관악구', '서울 관악구 남부순환로 1515 (신림동)', 1858, 1798, 0, 1, 0, 0, 0, 0, Decimal('37.48294960000000'), Decimal('126.91895530000000'))
(103, 'GS칼텍스', '지에스칼텍스㈜ 난곡주유소', '서울', '관악구', '서울 관악구 난곡로 206', 1879, 1804, 0, 0, 0, 0, 0, 0, Decimal('37.47340980000000'), Decimal('126.91879310000000'))
(104, '현대오일뱅크', '태양주유소', '서울', '광진구', '서울 광진구 동일로 345 (중곡동)', 1664, 1594, 0, 0, 0, 0, 0, 1, Decimal('37.56354400000001'), Decimal('127.08883040000000'))
(105, '현대오일뱅크', '(주)창원CW', '서울', '광진구', '서울 광진구 광나루로 460 (화양동)', 1665, 1595, 1, 1, 0, 0, 0, 0, Decimal('37.54510420000000'), Decimal('127.08049690000000'))
(106, '현대오일뱅크', 'HD현대오일뱅크㈜직영 능동주유소', '서울', '광진구', '서울 광진구 천호대로 584 (능동)', 1665, 1595, 1, 1, 0, 1, 0, 1, Decimal('37.55555510000000'), Decimal('127.08245500000000'))
(107, '현대오일뱅크', 'HD현대오일뱅크㈜직영 장호셀프주유소', '서울', '광진구', '서울 광진구 자양로 37 (자양동)', 1679, 1615, 1, 1, 0, 1, 0, 0, Decimal('37.53127830000000'), Decimal('127.08583250000000'))
(108, '현대오일뱅크', 'HD현대오일뱅크㈜직영 중원셀프주유소', '서울', '광진구', '서울 광진구 동일로 398 (중곡동)', 1679, 1609, 1, 1, 0, 0, 0, 0, Decimal('37.56354400000001'), Decimal('127.08883040000000'))
(109, '현대오일뱅크', 'HD현대오일뱅크㈜직영 중곡현대주유소', '서울', '광진구', '서울 광진구 동일로 435 (중곡동)', 1679, 1609, 1, 1, 0, 0, 0, 0, Decimal('37.56094119999999'), Decimal('127.09574580000000'))
(110, 'SK에너지', '(주)장수주유소', '서울', '광진구', '서울 광진구 동일로 266 (군자동)', 1694, 1594, 1, 0, 0, 1, 0, 1, Decimal('37.55497210000000'), Decimal('127.07151970000000'))
(111, 'S-OIL', '정해네트웍스(주)일진주유소', '서울', '광진구', '서울 광진구 동일로 413 (중곡동)', 1697, 1597, 1, 1, 0, 0, 0, 1, Decimal('37.56354400000001'), Decimal('127.08883040000000'))
(112, 'GS칼텍스', '용마주유소', '서울', '광진구', '서울 광진구 용마산로 68 (중곡동)', 1698, 1614, 0, 0, 0, 0, 0, 0, Decimal('37.55974870000000'), Decimal('127.08785530000000'))
(113, 'S-OIL', '대원주유소', '서울', '광진구', '서울 광진구 용마산로 122 (중곡동)', 1698, 1614, 0, 0, 0, 0, 0, 0, Decimal('37.56454770000000'), Decimal('127.08699600000000'))
(114, 'S-OIL', '삼호주유소', '서울', '광진구', '서울 광진구 천호대로 809 (광장동)', 1777, 1697, 1, 1, 0, 0, 0, 1, Decimal('37.54563560000000'), Decimal('127.10373410000000'))
(115, 'SK에너지', '유니스에너지 자양주유소', '서울', '광진구', '서울 광진구 아차산로 298 (자양동)', 1778, 1698, 0, 1, 0, 0, 0, 1, Decimal('37.53169200000000'), Decimal('127.07451600000000'))
(116, '현대오일뱅크', '㈜자연에너지 고척주유소', '서울', '구로구', '서울 구로구 고척로 199 (고척동)', 1605, 1585, 1, 1, 0, 0, 0, 0, Decimal('37.50512730000000'), Decimal('126.85544060000000'))
(117, 'SK에너지', '서서울고속주유소', '서울', '구로구', '서울 구로구 경인로 150 (오류동)', 1605, 1585, 1, 1, 0, 0, 0, 1, Decimal('37.49167509999999'), Decimal('126.84284180000000'))
(118, '현대오일뱅크', '(주)서울에너지 궁동주유소', '서울', '구로구', '서울 구로구 오리로 1299 (궁동)', 1605, 1585, 1, 0, 0, 0, 0, 0, Decimal('37.50043890000000'), Decimal('126.82852960000000'))
(119, '현대오일뱅크', '신성주유소', '서울', '구로구', '서울 구로구 구로동로 187 (구로제2동)', 1635, 1575, 1, 1, 0, 0, 0, 0, Decimal('37.49515880000000'), Decimal('126.88238860000000'))
(120, 'GS칼텍스', '(주)한미석유구로그린주유소', '서울', '구로구', '서울 구로구 구로중앙로 76 (구로동)', 1636, 1575, 1, 1, 0, 1, 0, 0, Decimal('37.49630640000000'), Decimal('126.88844440000000'))
(121, 'S-OIL', '극동유화(주) 항동주유소', '서울', '구로구', '서울 구로구 서해안로 2154 (항동)', 1655, 1585, 1, 1, 0, 0, 0, 0, Decimal('37.48343910000000'), Decimal('126.82782790000000'))
(122, 'GS칼텍스', '대성산업(주)디큐브주유소', '서울', '구로구', '서울 구로구 경인로 650 (신도림동)', 1659, 1574, 0, 0, 0, 0, 0, 1, Decimal('37.50788550000000'), Decimal('126.88708740000000'))
(123, 'SK에너지', 'SK구로주유소', '서울', '구로구', '서울 구로구 구일로 94 (구로동)', 1664, 1634, 0, 1, 0, 0, 0, 0, Decimal('37.49360180000000'), Decimal('126.87218900000000'))
(124, 'SK에너지', '구인주유소', '서울', '구로구', '서울 구로구 경인로 558 (구로동)', 1664, 1634, 0, 1, 0, 1, 1, 0, Decimal('37.50427790000000'), Decimal('126.88609440000000'))
(125, 'S-OIL', '남선석유(주)풀페이주유소', '서울', '구로구', '서울 구로구 경인로 41 (온수동)', 1669, 1637, 1, 1, 0, 0, 0, 0, Decimal('37.49032450000000'), Decimal('126.82560210000000'))
(126, '현대오일뱅크', '개봉주유소', '서울', '구로구', '서울 구로구 고척로 115 (개봉동)', 1697, 1677, 1, 1, 0, 0, 0, 0, Decimal('37.50193720000001'), Decimal('126.84681750000000'))
(127, 'SK에너지', 'SK에너지(주)직영 개봉동주유소', '서울', '구로구', '서울 구로구 경인로 290 (개봉동)', 1697, 1634, 0, 1, 0, 0, 0, 0, Decimal('37.48638990000000'), Decimal('126.85676750000000'))

In [14]:
#csv 파일로 저장
num_fields = len(cur.description)
field_names = [i[0] for i in cur.description]

df = pd.DataFrame(result)
df.columns = field_names

df.to_csv("gas_station_output.csv", index = False, encoding = 'utf-8')
df.head()

,id,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hours,lat,lng
0,1,현대오일뱅크,삼성동주유소,서울,강남구,서울 강남구 테헤란로 619 (삼성동),1719,1705,1,1,0,0,0,0,37.50985760000000,127.06511010000000
1,2,SK에너지,(주)보성 세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1723,1663,1,1,0,0,0,0,37.46715650000000,127.11870810000000
2,3,현대오일뱅크,HD현대오일뱅크㈜직영 산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1748,1678,1,1,0,0,0,0,37.46656750000000,127.11908030000000
3,4,현대오일뱅크,HD현대오일뱅크㈜직영 도곡셀프주유소,서울,강남구,서울 강남구 남부순환로 2718 (도곡2동),1754,1699,1,1,0,1,0,0,37.48546230000000,127.04321810000000
4,5,GS칼텍스,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1757,1689,1,1,0,0,0,0,37.47499260000000,127.10688660000000

In [15]:
#확인
df = pd.read_csv('./gas_station_output.csv', index_col = 0, thousands=',', encoding = 'utf-8')
df.head()

,brand,name,city,gu,address,gasoline,diesel,self,car_wash,charging_station,car_maintenance,convenience_store,24_hours,lat,lng
id,,,,,,,,,,,,,,,
1,현대오일뱅크,삼성동주유소,서울,강남구,서울 강남구 테헤란로 619 (삼성동),1719,1705,1,1,0,0,0,0,37.509858,127.065110
2,SK에너지,(주)보성 세곡주유소,서울,강남구,서울 강남구 헌릉로 731 (세곡동),1723,1663,1,1,0,0,0,0,37.467157,127.118708
3,현대오일뱅크,HD현대오일뱅크㈜직영 산성셀프주유소,서울,강남구,서울 강남구 헌릉로 730,1748,1678,1,1,0,0,0,0,37.466567,127.119080
4,현대오일뱅크,HD현대오일뱅크㈜직영 도곡셀프주유소,서울,강남구,서울 강남구 남부순환로 2718 (도곡2동),1754,1699,1,1,0,1,0,0,37.485462,127.043218
5,GS칼텍스,방죽주유소,서울,강남구,서울 강남구 밤고개로 215 (율현동),1757,1689,1,1,0,0,0,0,37.474993,127.106887

문제 6.

위도, 경도 정보를 이용하여 미왕빌딩에서 1킬로 이내에 위치한 주유소 정보를 검색하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 미왕빌딩으로 부터의 거리 (km)

제출 6.
- 쿼리, 결과

In [16]:
#미왕빌딩 위도, 경도 찾기
miwang = '서울 강남구 강남대로 364'
lat, lng = get_latlng(miwang)

print(lat, lng)

37.4955525 127.0292924

In [17]:
sql = "SELECT s.id, b.name, s.name, s.address, \
(6371 * acos(cos(radians(s.lat)) * cos(radians(37.4955525)) * cos(radians(127.0292924)-radians(s.lng)) + sin(radians(s.lat)) * sin(radians(37.4955525)))) distance \
FROM GAS_BRAND b, GAS_STATION s \
WHERE s.brand = b.id HAVING distance <= 1 ORDER BY distance"

cur.execute(sql)
result = cur.fetchall()

for row in result:
    print(row)

(15, 'SK에너지', 'SK서광주유소', '서울 강남구 역삼로 142', 0.5290118003680623)
(249, '현대오일뱅크', 'HD현대오일뱅크㈜직영 서초제일주유소', '서울 서초구 사임당로 116 (서초동)', 0.810302071851788)
(8, 'S-OIL', '극동유화㈜ 개나리주유소', '서울 강남구 언주로 423 (역삼동)', 0.9586506087505116)

문제 7.

위도, 경도 정보를 이용하여 미왕빌딩에서 셀프주유가 가능하고 24시간이면서 편의점이 있는 가장 가까운 주유소 10개를 휘 발유 가격이 가장 저렴한 순으로 정렬하여 조회하세요.

- 주유소 아이디, 주유소 브랜드명, 주유소 매장명, 주소, 휘발유 가격, 부가정보 (셀프, 24시간, 편의점 여부), 미왕빌딩으로 부터의 거리 (km)


제출 7.
- 쿼리, 결과

In [18]:
sql = "SELECT s.id, b.name 'brand', s.name, s.address, s.gasoline, s.self, s.24_hours, s.convenience_store, \
(6371 * acos(cos(radians(s.lat)) * cos(radians(37.4955525)) * cos(radians(127.0292924)-radians(s.lng)) + sin(radians(s.lat)) * sin(radians(37.4955525)))) distance \
FROM GAS_BRAND b, GAS_STATION s \
WHERE s.brand = b.id AND s.self = 1 AND s.24_hours = 1 AND s.convenience_store = 1 \
ORDER BY distance limit 10;"

cur.execute(sql)
result = cur.fetchall()

for row in result:
    print(row)

(242, 'SK에너지', '대신석유(주)대우주유소', '서울 서초구 양재대로 173 (양재동)', 1759, 1, 1, 1, 3.710853513300673)
(228, '알뜰주유소', '만남의광장주유소', '서울 서초구 양재대로12길 73-71', 1634, 1, 1, 1, 4.10436074733395)
(302, 'GS칼텍스', '지에스칼텍스(주)가든파이브주유소', '서울 송파구 탄천동로 740', 1723, 1, 1, 1, 5.292839133733846)
(310, 'SK에너지', '백제고분로주유소', '서울 송파구 오금로 143 (방이동)', 1723, 1, 1, 1, 7.945511550872455)
(224, 'SK에너지', '행촌제2주유소', '서울 서대문구 성산로 490 (대신동)', 1732, 1, 1, 1, 10.698555207712348)
(350, 'SK에너지', '행촌주유소', '서울 영등포구 도신로 130 (신길동)', 1633, 1, 1, 1, 10.95206129244323)
(364, 'SK에너지', 'SK에너지(주) 기린주유소', '서울 영등포구 선유로 270', 1699, 1, 1, 1, 12.320099598251995)
(138, 'GS칼텍스', '대득에너지(금천셀프주유소)', '서울 금천구 시흥대로 81 (시흥동)', 1675, 1, 1, 1, 12.680549557455187)
(214, '현대오일뱅크', '(주)가재울뉴타운주유소', '서울 서대문구 모래내로 205', 1690, 1, 1, 1, 12.78514726887763)
(339, '현대오일뱅크', '현대오일뱅크(주)직영 양천현대셀프주유소', '서울 양천구 안양천로 1179 (목동)', 1699, 1, 1, 1, 14.200831514321154)

문제 8.

구별로 주유소 브랜드 별 휘발유 평균가격을 조회하여 저렴한 순으로 출력하세요.

- 구 이름, 주유소 브랜드 이름, 휘발유 평균 가격

제출 8.
- 쿼리, 결과

In [19]:
sql = "SELECT s.gu, b.name, AVG(s.gasoline) avg \
FROM GAS_BRAND b, GAS_STATION s \
WHERE b.id = s.brand GROUP BY s.gu, b.name ORDER BY s.gu, avg;"

cur.execute(sql)
result = cur.fetchall()

for row in result:
    print(row)

('강남구', 'S-OIL', Decimal('1896.2500'))
('강남구', 'SK에너지', Decimal('1911.0000'))
('강남구', '현대오일뱅크', Decimal('2006.1250'))
('강남구', 'GS칼텍스', Decimal('2047.6667'))
('강동구', 'GS칼텍스', Decimal('1804.0000'))
('강동구', 'SK에너지', Decimal('1816.3333'))
('강동구', '현대오일뱅크', Decimal('1819.3333'))
('강동구', 'S-OIL', Decimal('1959.0000'))
('강북구', '현대오일뱅크', Decimal('1651.0000'))
('강북구', 'S-OIL', Decimal('1664.0000'))
('강북구', 'GS칼텍스', Decimal('1669.0000'))
('강북구', 'SK에너지', Decimal('1677.0000'))
('강서구', '알뜰주유소', Decimal('1634.5000'))
('강서구', '현대오일뱅크', Decimal('1693.7500'))
('강서구', 'SK에너지', Decimal('1741.3636'))
('강서구', 'GS칼텍스', Decimal('1750.1429'))
('강서구', 'S-OIL', Decimal('1751.5000'))
('관악구', '알뜰주유소', Decimal('1698.0000'))
('관악구', 'SK에너지', Decimal('1718.5000'))
('관악구', '현대오일뱅크', Decimal('1722.5000'))
('관악구', 'S-OIL', Decimal('1797.0000'))
('관악구', 'GS칼텍스', Decimal('1820.6667'))
('광진구', '현대오일뱅크', Decimal('1671.8333'))
('광진구', 'GS칼텍스', Decimal('1698.0000'))
('광진구', 'S-OIL', Decimal('1724.0000'))
('광진구', 'SK에너지', Decimal('1736.0000'))
('구로구', 'SK에너지', Decimal('1657.5000'))
('구로구', '현대오일뱅크', Decimal('1709.2500'))
('구로구', 'S-OIL', Decimal('1772.7500'))
('구로구', 'GS칼텍스', Decimal('1878.3333'))
('금천구', 'S-OIL', Decimal('1665.0000'))
('금천구', '알뜰주유소', Decimal('1674.0000'))
('금천구', 'SK에너지', Decimal('1682.0000'))
('금천구', 'GS칼텍스', Decimal('1685.0000'))
('금천구', '현대오일뱅크', Decimal('1709.0000'))
('노원구', '현대오일뱅크', Decimal('1698.3333'))
('노원구', 'S-OIL', Decimal('1699.5000'))
('노원구', 'SK에너지', Decimal('1702.0000'))
('노원구', 'GS칼텍스', Decimal('1732.8000'))
('도봉구', 'SK에너지', Decimal('1655.0000'))
('도봉구', 'GS칼텍스', Decimal('1668.3333'))
('도봉구', 'S-OIL', Decimal('1669.2000'))
('도봉구', '현대오일뱅크', Decimal('1670.8333'))
('동대문구', 'GS칼텍스', Decimal('1678.3333'))
('동대문구', 'SK에너지', Decimal('1688.6000'))
('동대문구', '현대오일뱅크', Decimal('1698.6667'))
('동대문구', 'S-OIL', Decimal('1704.7500'))
('동작구', 'GS칼텍스', Decimal('1734.0000'))
('동작구', 'S-OIL', Decimal('1739.0000'))
('동작구', '현대오일뱅크', Decimal('1755.0000'))
('동작구', 'SK에너지', Decimal('1875.0000'))
('마포구', '현대오일뱅크', Decimal('1723.0000'))
('마포구', 'SK에너지', Decimal('1768.6000'))
('마포구', 'S-OIL', Decimal('1770.0000'))
('서대문구', '현대오일뱅크', Decimal('1699.2500'))
('서대문구', 'GS칼텍스', Decimal('1703.5000'))
('서대문구', 'S-OIL', Decimal('1707.0000'))
('서대문구', 'SK에너지', Decimal('1732.1667'))
('서초구', '알뜰주유소', Decimal('1634.0000'))
('서초구', '현대오일뱅크', Decimal('1759.6000'))
('서초구', 'GS칼텍스', Decimal('1764.4545'))
('서초구', 'SK에너지', Decimal('1814.1429'))
('서초구', 'S-OIL', Decimal('1820.6667'))
('성동구', '자가상표', Decimal('1678.0000'))
('성동구', 'S-OIL', Decimal('1683.5000'))
('성동구', '현대오일뱅크', Decimal('1827.3333'))
('성동구', 'SK에너지', Decimal('1892.8333'))
('성동구', 'GS칼텍스', Decimal('2022.6667'))
('성북구', '알뜰주유소', Decimal('1643.0000'))
('성북구', '현대오일뱅크', Decimal('1685.4286'))
('성북구', 'SK에너지', Decimal('1694.0000'))
('성북구', 'S-OIL', Decimal('1699.1667'))
('성북구', 'GS칼텍스', Decimal('1701.6667'))
('송파구', 'S-OIL', Decimal('1728.2000'))
('송파구', '현대오일뱅크', Decimal('1745.5000'))
('송파구', 'GS칼텍스', Decimal('1751.8750'))
('송파구', 'SK에너지', Decimal('1760.4444'))
('양천구', '알뜰주유소', Decimal('1635.0000'))
('양천구', 'S-OIL', Decimal('1637.0000'))
('양천구', 'GS칼텍스', Decimal('1668.8000'))
('양천구', 'SK에너지', Decimal('1695.7500'))
('양천구', '현대오일뱅크', Decimal('1701.2222'))
('영등포구', '알뜰주유소', Decimal('1634.0000'))
('영등포구', 'S-OIL', Decimal('1672.6667'))
('영등포구', '현대오일뱅크', Decimal('1729.0000'))
('영등포구', 'SK에너지', Decimal('1791.0000'))
('영등포구', 'GS칼텍스', Decimal('1811.0000'))
('용산구', '현대오일뱅크', Decimal('2089.2500'))
('용산구', 'SK에너지', Decimal('2235.5000'))
('용산구', 'GS칼텍스', Decimal('2423.5000'))
('은평구', '현대오일뱅크', Decimal('1652.7500'))
('은평구', 'SK에너지', Decimal('1685.6667'))
('은평구', 'GS칼텍스', Decimal('1689.8000'))
('은평구', 'S-OIL', Decimal('1709.5000'))
('은평구', '자가상표', Decimal('1798.0000'))
('종로구', '현대오일뱅크', Decimal('1809.5000'))
('종로구', 'S-OIL', Decimal('1864.5000'))
('종로구', 'SK에너지', Decimal('2168.0000'))
('종로구', 'GS칼텍스', Decimal('2370.0000'))
('중구', 'S-OIL', Decimal('1702.0000'))
('중구', '알뜰주유소', Decimal('1758.0000'))
('중구', '현대오일뱅크', Decimal('1888.0000'))
('중구', 'SK에너지', Decimal('2089.8000'))
('중구', 'GS칼텍스', Decimal('2469.0000'))
('중랑구', '현대오일뱅크', Decimal('1647.0000'))
('중랑구', 'GS칼텍스', Decimal('1653.6667'))
('중랑구', 'S-OIL', Decimal('1673.6000'))
('중랑구', 'SK에너지', Decimal('1715.5000'))

In [20]:
conn.close()

---